split = {
    'multiwoz23': {
        0: {
            'valid_ood_label': 'Inform-Taxi-Arrive,Inform-Taxi-Dest,Request-Taxi-Phone,Request-Taxi-Dest,Inform-Taxi-Car,Inform-Taxi-none,Request-Taxi-Depart,Request-Taxi-Car,Request-Taxi-Arrive,Request-Taxi-Leave,Inform-Taxi-Leave,Inform-Taxi-Depart,Request-Train-Ticket,OfferBook-Train-none,Request-Train-Leave,Inform-Train-Depart,OfferBooked-Train-Dest,Inform-Train-Leave,NoOffer-Train-Depart,Request-Train-People,Inform-Train-none,Inform-Train-Id,Request-Train-Arrive,Inform-Train-Dest,Request-Train-Day,Request-Train-Time,Inform-Train-Day,OfferBooked-Train-Arrive,Request-Train-Id,Inform-Train-People,Request-Train-Dest,Inform-Train-Arrive,Inform-Train-Ticket,OfferBooked-Train-Ref,OfferBooked-Train-Id,NoOffer-Train-none,Request-Train-Depart,Request-Train-Ref',
            'test_ood_label': 'Request-Hotel-Internet,Inform-Hotel-Choice,Inform-Hotel-Stars,Recommend-Hotel-Name,Inform-Hotel-Parking,Request-Hotel-Name,Request-Hotel-Stars,Request-Hotel-Type,Request-Hotel-Ref,Inform-Hotel-Internet,Request-Hotel-Addr,Inform-Hotel-Price,Inform-Hotel-Name,Inform-Hotel-Area,Request-Hotel-Parking,Inform-Hotel-Type,Request-Hotel-Area,Inform-Hotel-Day,Inform-Hotel-none,Inform-Hotel-Stay,Request-Hotel-Post,Select-Hotel-none,Request-Hotel-Phone,NoOffer-Hotel-none,Inform-Hotel-Addr,Request-Hotel-Price,Inform-Hotel-People,Inform-Attraction-Name,Select-Attraction-Fee,Recommend-Attraction-Name,Request-Attraction-Post,Request-Attraction-Fee,Request-Attraction-Type,Request-Attraction-Addr,Request-Attraction-Phone,Request-Attraction-Area,Inform-Attraction-Choice,Request-Attraction-Name,Inform-Attraction-Area,Inform-Attraction-Addr,Inform-Attraction-Type,Inform-Attraction-none,Recommend-Attraction-Post,NoOffer-Attraction-none,Inform-Attraction-Fee'},
        1: {
            'valid_ood_label': 'Request-Hotel-Internet,Inform-Hotel-Choice,Inform-Hotel-Stars,Recommend-Hotel-Name,Inform-Hotel-Parking,Request-Hotel-Name,Request-Hotel-Stars,Request-Hotel-Type,Request-Hotel-Ref,Inform-Hotel-Internet,Request-Hotel-Addr,Inform-Hotel-Price,Inform-Hotel-Name,Inform-Hotel-Area,Request-Hotel-Parking,Inform-Hotel-Type,Request-Hotel-Area,Inform-Hotel-Day,Inform-Hotel-none,Inform-Hotel-Stay,Request-Hotel-Post,Select-Hotel-none,Request-Hotel-Phone,NoOffer-Hotel-none,Inform-Hotel-Addr,Request-Hotel-Price,Inform-Hotel-People,Inform-Taxi-Arrive,Inform-Taxi-Dest,Request-Taxi-Phone,Request-Taxi-Dest,Inform-Taxi-Car,Inform-Taxi-none,Request-Taxi-Depart,Request-Taxi-Car,Request-Taxi-Arrive,Request-Taxi-Leave,Inform-Taxi-Leave,Inform-Taxi-Depart',
            'test_ood_label': 'Inform-Attraction-Name,Select-Attraction-Fee,Recommend-Attraction-Name,Request-Attraction-Post,Request-Attraction-Fee,Request-Attraction-Type,Request-Attraction-Addr,Request-Attraction-Phone,Request-Attraction-Area,Inform-Attraction-Choice,Request-Attraction-Name,Inform-Attraction-Area,Inform-Attraction-Addr,Inform-Attraction-Type,Inform-Attraction-none,Recommend-Attraction-Post,NoOffer-Attraction-none,Inform-Attraction-Fee,Request-Train-Ticket,OfferBook-Train-none,Request-Train-Leave,Inform-Train-Depart,OfferBooked-Train-Dest,Inform-Train-Leave,NoOffer-Train-Depart,Request-Train-People,Inform-Train-none,Inform-Train-Id,Request-Train-Arrive,Inform-Train-Dest,Request-Train-Day,Request-Train-Time,Inform-Train-Day,OfferBooked-Train-Arrive,Request-Train-Id,Inform-Train-People,Request-Train-Dest,Inform-Train-Arrive,Inform-Train-Ticket,OfferBooked-Train-Ref,OfferBooked-Train-Id,NoOffer-Train-none,Request-Train-Depart,Request-Train-Ref'},
        2: {
            'valid_ood_label': 'Inform-Taxi-Arrive,Inform-Taxi-Dest,Request-Taxi-Phone,Request-Taxi-Dest,Inform-Taxi-Car,Inform-Taxi-none,Request-Taxi-Depart,Request-Taxi-Car,Request-Taxi-Arrive,Request-Taxi-Leave,Inform-Taxi-Leave,Inform-Taxi-Depart,Request-Train-Ticket,OfferBook-Train-none,Request-Train-Leave,Inform-Train-Depart,OfferBooked-Train-Dest,Inform-Train-Leave,NoOffer-Train-Depart,Request-Train-People,Inform-Train-none,Inform-Train-Id,Request-Train-Arrive,Inform-Train-Dest,Request-Train-Day,Request-Train-Time,Inform-Train-Day,OfferBooked-Train-Arrive,Request-Train-Id,Inform-Train-People,Request-Train-Dest,Inform-Train-Arrive,Inform-Train-Ticket,OfferBooked-Train-Ref,OfferBooked-Train-Id,NoOffer-Train-none,Request-Train-Depart,Request-Train-Ref',
            'test_ood_label': 'Request-Hotel-Internet,Inform-Hotel-Choice,Inform-Hotel-Stars,Recommend-Hotel-Name,Inform-Hotel-Parking,Request-Hotel-Name,Request-Hotel-Stars,Request-Hotel-Type,Request-Hotel-Ref,Inform-Hotel-Internet,Request-Hotel-Addr,Inform-Hotel-Price,Inform-Hotel-Name,Inform-Hotel-Area,Request-Hotel-Parking,Inform-Hotel-Type,Request-Hotel-Area,Inform-Hotel-Day,Inform-Hotel-none,Inform-Hotel-Stay,Request-Hotel-Post,Select-Hotel-none,Request-Hotel-Phone,NoOffer-Hotel-none,Inform-Hotel-Addr,Request-Hotel-Price,Inform-Hotel-People,Inform-Restaurant-Day,Request-Restaurant-Area,Inform-Restaurant-Name,Inform-Restaurant-Price,Request-Restaurant-Ref,Inform-Restaurant-none,Request-Restaurant-Post,Inform-Restaurant-Addr,NoOffer-Restaurant-none,Inform-Restaurant-People,Request-Restaurant-Name,Request-Restaurant-Food,Select-Restaurant-none,Request-Restaurant-Phone,Inform-Restaurant-Choice,Inform-Restaurant-Area,Request-Restaurant-Addr,Inform-Restaurant-Time,Request-Restaurant-Price,Inform-Restaurant-Food'},
        3: {
            'valid_ood_label': 'Request-Train-Ticket,OfferBook-Train-none,Request-Train-Leave,Inform-Train-Depart,OfferBooked-Train-Dest,Inform-Train-Leave,NoOffer-Train-Depart,Request-Train-People,Inform-Train-none,Inform-Train-Id,Request-Train-Arrive,Inform-Train-Dest,Request-Train-Day,Request-Train-Time,Inform-Train-Day,OfferBooked-Train-Arrive,Request-Train-Id,Inform-Train-People,Request-Train-Dest,Inform-Train-Arrive,Inform-Train-Ticket,OfferBooked-Train-Ref,OfferBooked-Train-Id,NoOffer-Train-none,Request-Train-Depart,Request-Train-Ref,Inform-Restaurant-Day,Request-Restaurant-Area,Inform-Restaurant-Name,Inform-Restaurant-Price,Request-Restaurant-Ref,Inform-Restaurant-none,Request-Restaurant-Post,Inform-Restaurant-Addr,NoOffer-Restaurant-none,Inform-Restaurant-People,Request-Restaurant-Name,Request-Restaurant-Food,Select-Restaurant-none,Request-Restaurant-Phone,Inform-Restaurant-Choice,Inform-Restaurant-Area,Request-Restaurant-Addr,Inform-Restaurant-Time,Request-Restaurant-Price,Inform-Restaurant-Food',
            'test_ood_label': 'Request-Hotel-Internet,Inform-Hotel-Choice,Inform-Hotel-Stars,Recommend-Hotel-Name,Inform-Hotel-Parking,Request-Hotel-Name,Request-Hotel-Stars,Request-Hotel-Type,Request-Hotel-Ref,Inform-Hotel-Internet,Request-Hotel-Addr,Inform-Hotel-Price,Inform-Hotel-Name,Inform-Hotel-Area,Request-Hotel-Parking,Inform-Hotel-Type,Request-Hotel-Area,Inform-Hotel-Day,Inform-Hotel-none,Inform-Hotel-Stay,Request-Hotel-Post,Select-Hotel-none,Request-Hotel-Phone,NoOffer-Hotel-none,Inform-Hotel-Addr,Request-Hotel-Price,Inform-Hotel-People,Inform-Taxi-Arrive,Inform-Taxi-Dest,Request-Taxi-Phone,Request-Taxi-Dest,Inform-Taxi-Car,Inform-Taxi-none,Request-Taxi-Depart,Request-Taxi-Car,Request-Taxi-Arrive,Request-Taxi-Leave,Inform-Taxi-Leave,Inform-Taxi-Depart'},
        4: {
            'valid_ood_label': 'Inform-Attraction-Name,Select-Attraction-Fee,Recommend-Attraction-Name,Request-Attraction-Post,Request-Attraction-Fee,Request-Attraction-Type,Request-Attraction-Addr,Request-Attraction-Phone,Request-Attraction-Area,Inform-Attraction-Choice,Request-Attraction-Name,Inform-Attraction-Area,Inform-Attraction-Addr,Inform-Attraction-Type,Inform-Attraction-none,Recommend-Attraction-Post,NoOffer-Attraction-none,Inform-Attraction-Fee,Inform-Restaurant-Day,Request-Restaurant-Area,Inform-Restaurant-Name,Inform-Restaurant-Price,Request-Restaurant-Ref,Inform-Restaurant-none,Request-Restaurant-Post,Inform-Restaurant-Addr,NoOffer-Restaurant-none,Inform-Restaurant-People,Request-Restaurant-Name,Request-Restaurant-Food,Select-Restaurant-none,Request-Restaurant-Phone,Inform-Restaurant-Choice,Inform-Restaurant-Area,Request-Restaurant-Addr,Inform-Restaurant-Time,Request-Restaurant-Price,Inform-Restaurant-Food',
            'test_ood_label': 'Request-Hotel-Internet,Inform-Hotel-Choice,Inform-Hotel-Stars,Recommend-Hotel-Name,Inform-Hotel-Parking,Request-Hotel-Name,Request-Hotel-Stars,Request-Hotel-Type,Request-Hotel-Ref,Inform-Hotel-Internet,Request-Hotel-Addr,Inform-Hotel-Price,Inform-Hotel-Name,Inform-Hotel-Area,Request-Hotel-Parking,Inform-Hotel-Type,Request-Hotel-Area,Inform-Hotel-Day,Inform-Hotel-none,Inform-Hotel-Stay,Request-Hotel-Post,Select-Hotel-none,Request-Hotel-Phone,NoOffer-Hotel-none,Inform-Hotel-Addr,Request-Hotel-Price,Inform-Hotel-People,Inform-Attraction-Name,Select-Attraction-Fee,Recommend-Attraction-Name,Request-Attraction-Post,Request-Attraction-Fee,Request-Attraction-Type,Request-Attraction-Addr,Request-Attraction-Phone,Request-Attraction-Area,Inform-Attraction-Choice,Request-Attraction-Name,Inform-Attraction-Area,Inform-Attraction-Addr,Inform-Attraction-Type,Inform-Attraction-none,Recommend-Attraction-Post,NoOffer-Attraction-none,Inform-Attraction-Fee'},
    },
    'mixsnips': {
        0: {'valid_ood_label': 'BookRestaurant,GetWeather', 'test_ood_label': 'PlayMusic,SearchScreeningEvent'},
        1: {'valid_ood_label': 'RateBook,BookRestaurant', 'test_ood_label': 'SearchScreeningEvent,SearchCreativeWork'},
        2: {'valid_ood_label': 'PlayMusic,RateBook', 'test_ood_label': 'AddToPlaylist,BookRestaurant'},
        3: {'valid_ood_label': 'BookRestaurant,SearchCreativeWork', 'test_ood_label': 'GetWeather,RateBook'},
        4: {'valid_ood_label': 'SearchScreeningEvent,GetWeather', 'test_ood_label': 'BookRestaurant,RateBook'},
    },
    'atis': {
        0: {
            'valid_ood_label': 'atis_aircraft,atis_flight_time,atis_ground_service,atis_quantity',
            'test_ood_label': 'atis_airfare,atis_ground_fare,atis_flight,atis_city'},
        1: {
            'valid_ood_label': 'atis_airline,atis_quantity,atis_cheapest,atis_ground_fare',
            'test_ood_label': 'atis_airfare,atis_aircraft,atis_flight,atis_ground_service'},
        2: {
            'valid_ood_label': 'atis_flight,atis_distance,atis_aircraft,atis_quantity',
            'test_ood_label': 'atis_day_name,atis_restriction,atis_airport,atis_capacity'},
        3: {
            'valid_ood_label': 'atis_flight_time,atis_cheapest,atis_meal,atis_ground_fare',
            'test_ood_label': 'atis_distance,atis_airline,atis_quantity,atis_airfare'},
        4: {
            'valid_ood_label': 'atis_day_name,atis_distance,atis_ground_service,atis_abbreviation',
            'test_ood_label': 'atis_flight_no,atis_airfare,atis_airport,atis_flight_time'}
    },
    'FSPS': {
        0: {
            'valid_ood_label': 'get_estimated_departure,get_location,get_contact,get_event_attendee,get_info_road_condition,update_directions',
            'test_ood_label': 'get_info_traffic,get_event_attendee_amount,get_event,combine,unintelligible,get_location_home'},
        1: {
            'valid_ood_label': 'unsupported_navigation,get_estimated_arrival,get_event,unsupported_event,negation,get_location',
            'test_ood_label': 'get_info_traffic,get_location_school,get_event_attendee_amount,get_distance,get_location_work,get_estimated_duration'},
        2: {
            'valid_ood_label': 'unsupported,get_estimated_duration,get_estimated_arrival,get_event_attendee_amount,get_contact,unsupported_navigation',
            'test_ood_label': 'get_estimated_departure,get_location_school,get_info_traffic,get_location_work,get_info_road_condition,unintelligible'},
        3: {
            'valid_ood_label': 'get_event_attendee_amount,get_estimated_duration,get_estimated_departure,get_location,get_event_attendee,get_directions',
            'test_ood_label': 'get_location_hometown,unsupported,unsupported_navigation,negation,get_distance,get_event'},
        4: {
            'valid_ood_label': 'unsupported_event,get_estimated_departure,get_event_organizer,get_info_road_condition,update_directions,get_distance',
            'test_ood_label': 'unsupported_navigation,get_location,negation,get_location_hometown,get_event_attendee,get_location_home'}
    }

}
