#dataset: 'multiwoz23'
dataset: 'atis'
split_index: 0

bert_path: 'bert-base-uncased'
bert_lr: 0.00001

#batch_size: 128
batch_size: 4
hidden_size: 768
early_stop: 5
epoch: 100
gpu: 0
lr: 0.001
seed: 0
save_threshold: 0.99
param_dir: 'params/'
l1: 1  # \lambda_1 in equation 7
