method: 'cl'
ood_method: 'nn_euler'  # logit or energy or lof
l3: 0  # \lambda_3 in equation 7 (for Section 5.6)
seed: 0
bert_dropout: 0.1
l2: 0.2
sim_method: 'euclidean'
k: 3
queue_size: 6500
m: 0.999  # momentum
cl_k: 25
T: 0.05
cl_method: label_representation